Jlee/tertiary style/#159
AlaskaAirlines/auro-button pull request #167
Opened 2022-07-21 21:29 UTC by leeejune

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** # (issue, if applicable)

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-08-22 17:54 UTC, blackfalcon commented
What issue is this addressing? And there is no summary of the change?

2022-08-22 18:18 UTC, leeejune commented
@blackfalcon Added the summary!

2022-08-22 20:45 UTC, blackfalcon requested changes

2022-08-22 20:45 UTC, blackfalcon commented on src/style.scss
> +$auro-rgb-color-base-white-03: rgba(255, 255, 255, .03);
I am confused as to why we need this? Are there not tokens for this? We really shouldn't be inventing colors in the scope of the element. 

If this PR is also using #159 why is this work not in the other PR?

2022-08-23 21:06 UTC, blackfalcon approved these changes

2022-08-23 21:06 UTC, merged