Create icon only button
AlaskaAirlines/auro-button pull request #201
Opened 2023-04-10 18:21 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #199 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

This PR reflects the creation of the icon only button, along with the necessary styles and example documentation for the new feature.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-04-10 18:35 UTC, jason-capsule42 requested changes
See my comment about aria-labels. Update that and then let's ship it!

2023-04-10 18:35 UTC, jason-capsule42 commented on demo/demo.md
> +  <auro-button iconOnly>
Can we update all these examples to include an `aria-label` attribute for voiceover support?

2023-04-11 03:31 UTC, blackfalcon requested changes
There are a lot of changes here that are not complete when trying to upgrade to a node 18/18 project. Karma is not compatible. Also, there are a number of packages that require node 18 to run. 

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@semantic-release/npm@10.0.3',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'env-ci@9.0.0',
npm WARN EBADENGINE   required: { node: '^16.14 || >=18' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'execa@7.1.1',
npm WARN EBADENGINE   required: { node: '^14.18.0 || ^16.14.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'semantic-release@21.0.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.5.2' }
npm WARN EBADENGINE }
```

I'd really suggest not doing the repo updates and keeping this work restricted to the scope of the update needed. We will address all the other updates in a PR similar to https://github.com/AlaskaAirlines/auro-badge/pull/45

2023-04-11 03:31 UTC, blackfalcon commented on package.json
> +    "node-sass": "^8.0.0",
This is not how we need to update to dart-sass. Please see this commit for all the details that are needed. 

https://github.com/AlaskaAirlines/auro-badge/pull/45/commits/f1edf77ba148adec56ebbd4fe0e2965ec9465977

By not updating wc-sass-render, you still have a dependency on node-sass. That's why the `node-sass` commands in the npm scripts are still working.

2023-04-12 20:56 UTC, jordanjones243 commented
Due to an error that could not be overcome within my local clone of `auro-button`, this PR will now be closed and the work in this PR will be reflected in another PR:
* https://github.com/AlaskaAirlines/auro-button/pull/202

2023-04-12 20:56 UTC, closed without merging